apiVersion: v1
kind: Service
metadata:
  name: crypto-recommendation-service
spec:
  selector:
    app: crypto-recommendation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
